# Generated by Django 3.1.1 on 2020-09-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_base',
            field=models.BooleanField(default=False, verbose_name='Is base currency?'),
        ),
    ]
