# Generated by Django 3.1.1 on 2020-09-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-date'], 'verbose_name': 'Rate', 'verbose_name_plural': 'Rates'},
        ),
        migrations.AlterField(
            model_name='rate',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
